project:
  type: website
  output-dir: docs

website:
  title: "Alex Greb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Baseball.qmd
      - Projects.qmd

format:
  html:
    theme: Superhero
    css: styles.css
    toc: true

editor: visual

