project:
  type: website
  output-dir: docs

website:
  title: "Alex Greb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Baseball.qmd
 
format:
  html:
    theme: 
      light: lux
      dark: Superhero
    css: styles.css
    toc: true

editor: visual

 